class PracticeFormPageLocator:
    FIRST_NAME = "#firstName"
    LAST_NAME = "#lastName"
    EMAIL = "#userEmail"
    GENDER_MALE = "#gender-radio-1"
    GENDER_FEMALE = "#gender-radio-2"
    GENDER_OTHER = "#gender-radio-3"
    PHONE_NUMBER = "#userNumber"
    BIRTH_DATE = "#dateOfBirthInput"
    SUBJECTS = "#subjectsContainer"
    HOBBY_SPORTS = "#hobbies-checkbox-1"
    HOBBY_READING = "#hobbies-checkbox-2"
    HOBBY_MUSIC = "#hobbies-checkbox-3"
    UPLOAD_PICTURE = "#uploadPicture"
    CURRENT_ADDRESS = "#currentAddress"
    STATE = "#react-select-3-input"
    CITY = "#react-select-4-input"
    SUBMIT = "#submit"
